import i18next from 'i18next';
import DocumentationNavigation from '../main/documentation/DocumentationNavigation';

import ar from './navigation-i18n/ar';
import fa from './navigation-i18n/fa';
import en from './navigation-i18n/en';
import tr from './navigation-i18n/tr';
import authRoles from '../auth/authRoles';

i18next.addResourceBundle('fa', 'navigation', fa);
i18next.addResourceBundle('en', 'navigation', en);
i18next.addResourceBundle('tr', 'navigation', tr);
i18next.addResourceBundle('ar', 'navigation', ar);

const navigationConfig = [
  {
    id: 'dashboards',
    title: 'Dashboards',
    translate: 'داشبرد',
    subtitle: 'طرح های سفارشی داشبورد',
    type: 'group',
    icon: 'heroicons-outline:home',
    children: [
      {
        id: 'dashboards.project',
        title: 'Project',
        translate: 'پروژه',
        type: 'item',
        icon: 'heroicons-outline:clipboard-check',
        url: '/dashboards/project',
      },
      {
        id: 'dashboards.analytics',
        title: 'Analytics',
        translate: 'آنالیز و تحلیل',
        type: 'item',
        icon: 'heroicons-outline:chart-pie',
        url: '/dashboards/analytics',
      },
      {
        id: 'dashboards.finance',
        title: 'Finance',
        translate: 'مالی',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/dashboards/finance',
      },
      {
        id: 'dashboards.crypto',
        title: 'Crypto',
        translate: 'کریپتو',
        type: 'item',
        icon: 'heroicons-outline:currency-dollar',
        url: '/dashboards/crypto',
      },
    ],
  },
  {
    id: 'apps',
    title: 'Applications',
    translate: 'اپلیکیشن ها',
    subtitle: 'برنامه های کاربردی و سفارشی',
    type: 'group',
    icon: 'heroicons-outline:cube',
    children: [
      {
        id: 'apps.academy',
        title: 'Academy',
        translate: 'آکادمی',
        type: 'item',
        icon: 'heroicons-outline:academic-cap',
        url: '/apps/academy',
      },
      {
        id: 'apps.calendar',
        title: 'Calendar',
        translate: 'تقویم',
        subtitle: '3 رویداد بعدی',
        type: 'item',
        icon: 'heroicons-outline:calendar',
        url: '/apps/calendar',
      },
      {
        id: 'apps.chat',
        title: 'Chat',
        translate: 'گفتگو',
        type: 'item',
        icon: 'heroicons-outline:chat-alt',
        url: '/apps/chat',
      },
      {
        id: 'apps.contacts',
        title: 'Contacts',
        translate: 'مخاطبین',
        type: 'item',
        icon: 'heroicons-outline:user-group',
        url: '/apps/contacts',
      },
      {
        id: 'apps.ecommerce',
        title: 'ECommerce',
        translate: 'تجارت الکترونیک',
        type: 'collapse',
        icon: 'heroicons-outline:shopping-cart',
        children: [
          {
            id: 'e-commerce-products',
            title: 'Products',
            translate: 'محصولات',
            type: 'item',
            url: 'apps/e-commerce/products',
            end: true,
          },
          {
            id: 'e-commerce-product-detail',
            title: 'جزییات محصول',
            translate: 'جزییات محصول',
            type: 'item',
            url: 'apps/e-commerce/products/1/a-walk-amongst-friends-canvas-print',
          },
          {
            id: 'e-commerce-new-product',
            title: 'New Product',
            translate: 'محصول جدید',
            type: 'item',
            url: 'apps/e-commerce/products/new',
          },
          {
            id: 'e-commerce-orders',
            title: 'Orders',
            translate: 'سفارش ها',
            type: 'item',
            url: 'apps/e-commerce/orders',
            end: true,
          },
          {
            id: 'e-commerce-order-detail',
            title: 'Order Detail',
            translate: 'جزئیات سفارش',
            type: 'item',
            url: 'apps/e-commerce/orders/1',
          },
        ],
      },
      {
        id: 'apps.file-manager',
        title: 'مدیریت فایل',
        translate: 'مدیریت فایل',
        type: 'item',
        icon: 'heroicons-outline:cloud',
        url: '/apps/file-manager',
        end: true,
      },
      {
        id: 'apps.help-center',
        title: 'Help Center',
        translate: 'مرکز کمک',
        type: 'collapse',
        icon: 'heroicons-outline:support',
        url: '/apps/help-center',
        children: [
          {
            id: 'apps.help-center.home',
            title: 'Home',
            translate: 'خانه',
            type: 'item',
            url: '/apps/help-center',
            end: true,
          },
          {
            id: 'apps.help-center.faqs',
            title: 'FAQs',
            translate: 'سوالات متداول',
            type: 'item',
            url: '/apps/help-center/faqs',
          },
          {
            id: 'apps.help-center.guides',
            title: 'Guides',
            translate: 'راهنما ها',
            type: 'item',
            url: '/apps/help-center/guides',
          },
          {
            id: 'apps.help-center.support',
            title: 'Support',
            translate: 'پشتیبانی',
            type: 'item',
            url: '/apps/help-center/support',
          },
        ],
      },
      {
        id: 'apps.mailbox',
        title: 'Mailbox',
        translate: 'صندوق پستی',
        type: 'item',
        icon: 'heroicons-outline:mail',
        url: '/apps/mailbox',
        badge: {
          title: '27',
          translate: '27',
          classes: 'px-8 bg-pink-600 text-white rounded-full',
        },
      },
      {
        id: 'apps.notes',
        title: 'Notes',
        translate: 'یادداشت ها',
        type: 'item',
        icon: 'heroicons-outline:pencil-alt',
        url: '/apps/notes',
      },
      {
        id: 'apps.scrumboard',
        title: 'Scrumboard',
        translate: 'اسکرام بورد',
        type: 'item',
        icon: 'heroicons-outline:view-boards',
        url: '/apps/scrumboard',
      },
      {
        id: 'apps.tasks',
        title: 'Tasks',
        translate: 'تسک ها',
        subtitle: '12 کار باقی مانده',
        type: 'item',
        icon: 'heroicons-outline:check-circle',
        url: '/apps/tasks',
      },
      {
        id: 'apps.profile',
        title: 'Profile',
        translate: 'پروفایل',
        type: 'item',
        icon: 'heroicons-outline:user-circle',
        url: '/apps/profile',
      },
    ],
  },
  {
    id: 'pages',
    title: 'Pages',
    translate: 'صفحات',
    subtitle: 'طرح های صفحات سفارشی',
    type: 'group',
    icon: 'heroicons-outline:document',
    children: [
      {
        id: 'pages.activities',
        title: 'Activities',
        translate: 'فعالیت ها',
        type: 'item',
        icon: 'heroicons-outline:menu-alt-2',
        url: '/pages/activities',
      },
      {
        id: 'pages.authentication',
        title: 'Authentication',
        translate: 'احراز هویت',
        type: 'collapse',
        icon: 'heroicons-outline:lock-closed',
        children: [
          {
            id: 'pages.authentication.sign-in',
            title: 'Sign in',
            translate: 'ورود',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.sign-in.classic',
                title: 'Classic',
                translate: 'کلاسیک',
                type: 'item',
                url: '/pages/authentication/sign-in/classic',
              },
              {
                id: 'pages.authentication.sign-in.modern',
                title: 'Modern',
                translate: 'مدرن',
                type: 'item',
                url: '/pages/authentication/sign-in/modern',
              },
              {
                id: 'pages.authentication.sign-in.modern-reversed',
                title: 'Modern Reversed',
                translate: 'مدرن معکوس',
                type: 'item',
                url: '/pages/authentication/sign-in/modern-reversed',
              },
              {
                id: 'pages.authentication.sign-in.split-screen',
                title: 'Split Screen',
                translate: 'تقسیم صفحه',
                type: 'item',
                url: '/pages/authentication/sign-in/split-screen',
              },
              {
                id: 'pages.authentication.sign-in.split-screen-reversed',
                title: 'Split Screen Reversed',
                translate: 'تقسیم صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/sign-in/split-screen-reversed',
              },
              {
                id: 'pages.authentication.sign-in.full-screen',
                title: 'Full Screen',
                translate: 'تمام صفحه',
                type: 'item',
                url: '/pages/authentication/sign-in/full-screen',
              },
              {
                id: 'pages.authentication.sign-in.full-screen-reversed',
                title: 'Full Screen Reversed',
                translate: 'تمام صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/sign-in/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.sign-up',
            title: 'Sign up',
            translate: 'ثبت نام',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.sign-up.classic',
                title: 'Classic',
                translate: 'کلاسیک',
                type: 'item',
                url: '/pages/authentication/sign-up/classic',
              },
              {
                id: 'pages.authentication.sign-up.modern',
                title: 'Modern',
                translate: 'مدرن',
                type: 'item',
                url: '/pages/authentication/sign-up/modern',
              },
              {
                id: 'pages.authentication.sign-up.modern-reversed',
                title: 'Modern Reversed',
                translate: 'مدرن معکوس',
                type: 'item',
                url: '/pages/authentication/sign-up/modern-reversed',
              },
              {
                id: 'pages.authentication.sign-up.split-screen',
                title: 'Split Screen',
                translate: 'تقسیم صفحه',
                type: 'item',
                url: '/pages/authentication/sign-up/split-screen',
              },
              {
                id: 'pages.authentication.sign-up.split-screen-reversed',
                title: 'Split Screen Reversed',
                translate: 'تقسیم صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/sign-up/split-screen-reversed',
              },
              {
                id: 'pages.authentication.sign-up.full-screen',
                title: 'Full Screen',
                translate: 'تمام صفحه',
                type: 'item',
                url: '/pages/authentication/sign-up/full-screen',
              },
              {
                id: 'pages.authentication.sign-up.full-screen-reversed',
                title: 'Full Screen Reversed',
                translate: 'تمام صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/sign-up/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.sign-out',
            title: 'خروج از حساب کاربری',
            translate: 'خروج از حساب کاربری',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.sign-out.classic',
                title: 'Classic',
                translate: 'کلاسیک',
                type: 'item',
                url: '/pages/authentication/sign-out/classic',
              },
              {
                id: 'pages.authentication.sign-out.modern',
                title: 'Modern',
                translate: 'مدرن',
                type: 'item',
                url: '/pages/authentication/sign-out/modern',
              },
              {
                id: 'pages.authentication.sign-out.modern-reversed',
                title: 'Modern Reversed',
                translate: 'مدرن معکوس',
                type: 'item',
                url: '/pages/authentication/sign-out/modern-reversed',
              },
              {
                id: 'pages.authentication.sign-out.split-screen',
                title: 'Split Screen',
                translate: 'تقسیم صفحه',
                type: 'item',
                url: '/pages/authentication/sign-out/split-screen',
              },
              {
                id: 'pages.authentication.sign-out.split-screen-reversed',
                title: 'Split Screen Reversed',
                translate: 'تقسیم صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/sign-out/split-screen-reversed',
              },
              {
                id: 'pages.authentication.sign-out.full-screen',
                title: 'Full Screen',
                translate: 'تمام صفحه',
                type: 'item',
                url: '/pages/authentication/sign-out/full-screen',
              },
              {
                id: 'pages.authentication.sign-out.full-screen-reversed',
                title: 'Full Screen Reversed',
                translate: 'تمام صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/sign-out/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.forgot-password',
            title: 'Forgot password',
            translate: 'فراموشی رمز عبور',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.forgot-password.classic',
                title: 'Classic',
                translate: 'کلاسیک',
                type: 'item',
                url: '/pages/authentication/forgot-password/classic',
              },
              {
                id: 'pages.authentication.forgot-password.modern',
                title: 'Modern',
                translate: 'مدرن',
                type: 'item',
                url: '/pages/authentication/forgot-password/modern',
              },
              {
                id: 'pages.authentication.forgot-password.modern-reversed',
                title: 'Modern Reversed',
                translate: 'مدرن معکوس',
                type: 'item',
                url: '/pages/authentication/forgot-password/modern-reversed',
              },
              {
                id: 'pages.authentication.forgot-password.split-screen',
                title: 'Split Screen',
                translate: 'تقسیم صفحه',
                type: 'item',
                url: '/pages/authentication/forgot-password/split-screen',
              },
              {
                id: 'pages.authentication.forgot-password.split-screen-reversed',
                title: 'Split Screen Reversed',
                translate: 'تقسیم صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/forgot-password/split-screen-reversed',
              },
              {
                id: 'pages.authentication.forgot-password.full-screen',
                title: 'Full Screen',
                translate: 'تمام صفحه',
                type: 'item',
                url: '/pages/authentication/forgot-password/full-screen',
              },
              {
                id: 'pages.authentication.forgot-password.full-screen-reversed',
                title: 'Full Screen Reversed',
                translate: 'تمام صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/forgot-password/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.reset-password',
            title: 'Reset password',
            translate: 'بازنشانی رمز عبور',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.reset-password.classic',
                title: 'Classic',
                translate: 'کلاسیک',
                type: 'item',
                url: '/pages/authentication/reset-password/classic',
              },
              {
                id: 'pages.authentication.reset-password.modern',
                title: 'Modern',
                translate: 'مدرن',
                type: 'item',
                url: '/pages/authentication/reset-password/modern',
              },
              {
                id: 'pages.authentication.reset-password.modern-reversed',
                title: 'Modern Reversed',
                translate: 'مدرن معکوس',
                type: 'item',
                url: '/pages/authentication/reset-password/modern-reversed',
              },
              {
                id: 'pages.authentication.reset-password.split-screen',
                title: 'Split Screen',
                translate: 'تقسیم صفحه',
                type: 'item',
                url: '/pages/authentication/reset-password/split-screen',
              },
              {
                id: 'pages.authentication.reset-password.split-screen-reversed',
                title: 'Split Screen Reversed',
                   translate: 'تقسیم صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/reset-password/split-screen-reversed',
              },
              {
                id: 'pages.authentication.reset-password.full-screen',
                title: 'Full Screen',
                translate: 'تمام صفحه',
                type: 'item',
                url: '/pages/authentication/reset-password/full-screen',
              },
              {
                id: 'pages.authentication.reset-password.full-screen-reversed',
                title: 'Full Screen Reversed',
                translate: 'تمام صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/reset-password/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.unlock-session',
            title: 'Unlock session',
            translate: 'باز کردن قفل session',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.unlock-session.classic',
                title: 'Classic',
               translate: 'کلاسیک',
                type: 'item',
                url: '/pages/authentication/unlock-session/classic',
              },
              {
                id: 'pages.authentication.unlock-session.modern',
                title: 'Modern',
                translate: 'مدرن',
                type: 'item',
                url: '/pages/authentication/unlock-session/modern',
              },
              {
                id: 'pages.authentication.unlock-session.modern-reversed',
                title: 'Modern Reversed',
                translate: 'مدرن معکوس',
                type: 'item',
                url: '/pages/authentication/unlock-session/modern-reversed',
              },
              {
                id: 'pages.authentication.unlock-session.split-screen',
                title: 'Split Screen',
                translate: 'تقسیم صفحه',
                type: 'item',
                url: '/pages/authentication/unlock-session/split-screen',
              },
              {
                id: 'pages.authentication.unlock-session.split-screen-reversed',
                title: 'Split Screen Reversed',
                   translate: 'تقسیم صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/unlock-session/split-screen-reversed',
              },
              {
                id: 'pages.authentication.unlock-session.full-screen',
                title: 'Full Screen',
                translate: 'تمام صفحه',
                type: 'item',
                url: '/pages/authentication/unlock-session/full-screen',
              },
              {
                id: 'pages.authentication.unlock-session.full-screen-reversed',
                title: 'Full Screen Reversed',
                translate: 'تمام صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/unlock-session/full-screen-reversed',
              },
            ],
          },
          {
            id: 'pages.authentication.confirmation-required',
            title: 'نیازمند تایید',
            translate: 'نیازمند تایید',
            type: 'collapse',
            children: [
              {
                id: 'pages.authentication.confirmation-required.classic',
                title: 'Classic',
               translate: 'کلاسیک',
                type: 'item',
                url: '/pages/authentication/confirmation-required/classic',
              },
              {
                id: 'pages.authentication.confirmation-required.modern',
                title: 'Modern',
                translate: 'مدرن',
                type: 'item',
                url: '/pages/authentication/confirmation-required/modern',
              },
              {
                id: 'pages.authentication.confirmation-required.modern-reversed',
                title: 'Modern Reversed',
                translate: 'مدرن معکوس',
                type: 'item',
                url: '/pages/authentication/confirmation-required/modern-reversed',
              },
              {
                id: 'pages.authentication.confirmation-required.split-screen',
                title: 'Split Screen',
                translate: 'تقسیم صفحه',
                type: 'item',
                url: '/pages/authentication/confirmation-required/split-screen',
              },
              {
                id: 'pages.authentication.confirmation-required.split-screen-reversed',
                title: 'Split Screen Reversed',
                   translate: 'تقسیم صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/confirmation-required/split-screen-reversed',
              },
              {
                id: 'pages.authentication.confirmation-required.full-screen',
                title: 'Full Screen',
                translate: 'تمام صفحه',
                type: 'item',
                url: '/pages/authentication/confirmation-required/full-screen',
              },
              {
                id: 'pages.authentication.confirmation-required.full-screen-reversed',
                title: 'Full Screen Reversed',
                translate: 'تمام صفحه معکوس',
                type: 'item',
                url: '/pages/authentication/confirmation-required/full-screen-reversed',
              },
            ],
          },
        ],
      },
      {
        id: 'pages.coming-soon',
        title: 'Coming Soon',
        translate: 'به زودی',
        type: 'collapse',
        icon: 'heroicons-outline:clock',
        url: '/pages/coming-soon',
        children: [
          {
            id: 'pages.coming-soon.classic',
            title: 'Classic',
            translate: 'کلاسیک',
            type: 'item',
            url: '/pages/coming-soon/classic',
          },
          {
            id: 'pages.coming-soon.modern',
            title: 'Modern',
            translate: 'مدرن',
            type: 'item',
            url: '/pages/coming-soon/modern',
          },
          {
            id: 'pages.coming-soon.modern-reversed',
            title: 'Modern Reversed',
            translate: 'مدرن معکوس',
            type: 'item',
            url: '/pages/coming-soon/modern-reversed',
          },
          {
            id: 'pages.coming-soon.split-screen',
            title: 'Split Screen',
            translate: 'تقسیم صفحه',
            type: 'item',
            url: '/pages/coming-soon/split-screen',
          },
          {
            id: 'pages.coming-soon.split-screen-reversed',
            title: 'Split Screen Reversed',
            translate: 'تقسیم صفحه معکوس',
            type: 'item',
            url: '/pages/coming-soon/split-screen-reversed',
          },
          {
            id: 'pages.coming-soon.full-screen',
            title: 'Full Screen',
            translate: 'تمام صفحه',
            type: 'item',
            url: '/pages/coming-soon/full-screen',
          },
          {
            id: 'pages.coming-soon.full-screen-reversed',
            title: 'Full Screen Reversed',
            translate: 'تمام صحفه معکوس',
            type: 'item',
            url: '/pages/coming-soon/full-screen-reversed',
          },
        ],
      },
      {
        id: 'pages.error',
        title: 'Error',
        translate: 'خطا',
        type: 'collapse',
        icon: 'heroicons-outline:exclamation-circle',
        children: [
          {
            id: 'pages.error.404',
            title: '404',
            translate: '404',
            type: 'item',
            url: '/pages/error/404',
          },
          {
            id: 'pages.error.500',
            title: '500',
            translate: '500',
            type: 'item',
            url: '/pages/error/500',
          },
        ],
      },
      {
        id: 'pages.invoice',
        title: 'Invoice',
        translate: 'صورتحساب',
        type: 'collapse',
        icon: 'heroicons-outline:calculator',
        children: [
          {
            id: 'pages.invoice.printable',
            title: 'Printable',
            translate: 'قابل چاپ',
            type: 'collapse',
            children: [
              {
                id: 'pages.invoice.printable.compact',
                title: 'Compact',
                translate: 'فشرده',
                type: 'item',
                url: '/pages/invoice/printable/compact',
              },
              {
                id: 'pages.invoice.printable.modern',
                title: 'Modern',
                translate: 'مدرن',
                type: 'item',
                url: '/pages/invoice/printable/modern',
              },
            ],
          },
        ],
      },
      {
        id: 'pages.maintenance',
        title: 'Maintenance',
        translate: 'نگهداری',
        type: 'item',
        icon: 'heroicons-outline:exclamation',
        url: '/pages/maintenance',
      },
      {
        id: 'pages.pricing',
        title: 'Pricing',
        translate: 'قیمت گذاری',
        type: 'collapse',
        icon: 'heroicons-outline:cash',
        children: [
          {
            id: 'pages.pricing.modern',
            title: 'Modern',
            translate: 'مدرن',
            type: 'item',
            url: '/pages/pricing/modern',
          },
          {
            id: 'pages.pricing.simple',
            title: 'Simple',
            translate: 'ساده',
            type: 'item',
            url: '/pages/pricing/simple',
          },
          {
            id: 'pages.pricing.single',
            title: 'Single',
             translate: 'تنها',
            type: 'item',
            url: '/pages/pricing/single',
          },
          {
            id: 'pages.pricing.table',
            title: 'Table',
            translate: 'جدول',
            type: 'item',
            url: '/pages/pricing/table',
          },
        ],
      },
      {
        id: 'pages.search',
        title: 'Search',
        translate: 'جستجو',
        type: 'collapse',
        icon: 'search',
        children: [
          {
            id: 'pages.search.classic-search',
            title: 'Classic Search',
            translate: 'جستجوی کلاسیک',
            type: 'item',
            url: 'pages/search/classic',
          },
          {
            id: 'pages.search.modern-search',
            title: 'Modern Search',
            translate: 'جستجوی مدرن',
            type: 'item',
            url: 'pages/search/modern',
          },
        ],
      },
    ],
  },
  {
    id: 'user-interface',
    title: 'رابط کاربری',
    translate: 'User Interface',
    subtitle: 'بلوک های سازنده UI و UX',
    type: 'group',
    icon: 'heroicons-outline:collection',
    children: [
      {
        id: 'user-interface.tailwindcss',
        title: 'TailwindCSS',
        translate: 'TailwindCSS',
        type: 'item',
        icon: 'heroicons-outline:sparkles',
        url: '/ui/tailwindcss',
      },
      {
        id: 'user-interface.icons',
        title: 'Icons',
        translate: 'آیکون ها',
        type: 'collapse',
        icon: 'heroicons-outline:lightning-bolt',
        children: [
          {
            id: 'user-interface.icons.heroicons-outline',
            title: 'Heroicons Outline',
            translate: 'Heroicons Outline',
            type: 'item',
            url: '/ui/icons/heroicons/outline',
          },
          {
            id: 'user-interface.icons.heroicons-solid',
            title: 'Heroicons Solid',
            translate: 'Heroicons Solid',
            type: 'item',
            url: '/ui/icons/heroicons/solid',
          },
          {
            id: 'user-interface.icons.material-twotone',
            title: 'Material Twotone',
            translate: 'Material Twotone',
            type: 'item',
            url: '/ui/icons/material/twotone',
          },
          {
            id: 'user-interface.icons.material-outline',
            title: 'Material Outline',
            translate: 'Material Outline',
            type: 'item',
            url: '/ui/icons/material/outline',
          },
          {
            id: 'user-interface.icons.material-solid',
            title: 'Material Solid',
            translate: 'Material Solid',
            type: 'item',
            url: '/ui/icons/material/solid',
          },
          {
            id: 'user-interface.icons.feather',
            title: 'Feather',
            translate: 'Feather',
            type: 'item',
            url: '/ui/icons/feather',
          },
        ],
      },
      {
        id: 'user-interface.page-layouts',
        title: 'Page Layouts',
        translate: 'طرح بندی صفحات ',
        type: 'collapse',
        icon: 'heroicons-outline:template',
        children: [
          {
            id: 'user-interface.page-layouts.overview',
            title: 'Overview',
            translate: 'بررسی اجمالی',
            type: 'item',
            url: '/ui/page-layouts/overview',
          },
          {
            id: 'user-interface.page-layouts.carded',
            title: 'Carded',
            translate: 'کارت شده',
            type: 'collapse',
            children: [
              {
                id: 'user-interface.page-layouts.carded.full-width',
                title: 'Full Width',
                translate: 'تمام عرض',
                type: 'collapse',
                url: '/ui/page-layouts/carded/full-width',
                children: [
                  {
                    id: 'user-interface.page-layouts.carded.full-width.overview',
                    title: 'Full Width Overview',
                    translate: 'نمای کلی تمام عرض',
                    type: 'item',
                    url: '/ui/page-layouts/carded/full-width/overview',
                  },
                  {
                    id: 'user-interface.page-layouts.carded.full-width.normal-scroll',
                    title: 'Full Width Normal Scroll',
                    translate: 'اسکرول معمولی با عرض کامل',
                    type: 'item',
                    url: '/ui/page-layouts/carded/full-width/normal-scroll',
                  },
                  {
                    id: 'user-interface.page-layouts.carded.full-width.page-scroll',
                    title: 'Full Width Page Scroll',
                    translate: 'اسکرول صفحه با عرض کامل',
                    type: 'item',
                    url: '/ui/page-layouts/carded/full-width/page-scroll',
                  },
                  {
                    id: 'user-interface.page-layouts.carded.full-width.content-scroll',
                    title: 'Full Width Content Scroll',
                    translate: 'اسکرول محتوا با عرض کامل',
                    type: 'item',
                    url: '/ui/page-layouts/carded/full-width/content-scroll',
                  },
                ],
              },
              {
                id: 'user-interface.page-layouts.carded.with-sidebars',
                title: 'With Sidebars',
                translate: 'با سایدبارها',
                type: 'collapse',
                url: '/ui/page-layouts/carded/with-sidebars',
                children: [
                  {
                    id: 'user-interface.page-layouts.carded.with-sidebars.overview',
                    title: 'With Sidebars Overview',
                    translate: 'نمای کلی سایدبار دار ها',
                    type: 'item',
                    url: '/ui/page-layouts/carded/with-sidebars/overview',
                  },
                  {
                    id: 'user-interface.page-layouts.carded.with-sidebars.normal-scroll',
                    title: 'With Sidebars Normal Scroll',
                    translate: 'اسکرول نرمال سایدبار  دار',
                    type: 'item',
                    url: '/ui/page-layouts/carded/with-sidebars/normal-scroll',
                  },
                  {
                    id: 'user-interface.page-layouts.carded.with-sidebars.page-scroll',
                    title: 'With Sidebars Page Scroll',
                    translate: 'اسکرول صفحه سایدبار دار',
                    type: 'item',
                    url: '/ui/page-layouts/carded/with-sidebars/page-scroll',
                  },
                  {
                    id: 'user-interface.page-layouts.carded.with-sidebars.content-scroll',
                    title: 'With Sidebars Content Scroll',
                    translate: 'اسکرول محتوا سایدبار دار',
                    type: 'item',
                    url: '/ui/page-layouts/carded/with-sidebars/content-scroll',
                  },
                ],
              },
            ],
          },
          {
            id: 'user-interface.page-layouts.simple',
            title: 'Simple',
            translate: 'ساده',
            type: 'collapse',
            children: [
              {
                id: 'user-interface.page-layouts.simple.full-width',
                title: 'Full Width',
                translate: 'تمام عرض',
                type: 'collapse',
                url: '/ui/page-layouts/simple/full-width',
                children: [
                  {
                    id: 'user-interface.page-layouts.simple.full-width.overview',
                    title: 'Full Width Overview',
                    translate: 'نمای کلی تمام عرض',
                    type: 'item',
                    url: '/ui/page-layouts/simple/full-width/overview',
                  },
                  {
                    id: 'user-interface.page-layouts.simple.full-width.normal-scroll',
                    title: 'Full Width Normal Scroll',
                    translate: 'اسکرول عادی تمام عرض',
                    type: 'item',
                    url: '/ui/page-layouts/simple/full-width/normal-scroll',
                  },
                  {
                    id: 'user-interface.page-layouts.simple.full-width.page-scroll',
                    title: 'Full Width Page Scroll',
                    translate: 'اسکرول  صفحه تمام عرض',
                    type: 'item',
                    url: '/ui/page-layouts/simple/full-width/page-scroll',
                  },
                  {
                    id: 'user-interface.page-layouts.simple.full-width.content-scroll',
                    title: 'Full Width Content Scroll',
                    translate: 'اسکرول محتوا تمام عرض',
                    type: 'item',
                    url: '/ui/page-layouts/simple/full-width/content-scroll',
                  },
                ],
              },
              {
                id: 'user-interface.page-layouts.simple.with-sidebars',
                title: 'With Sidebars',
                translate: 'همراه با ساید بار',
                type: 'collapse',
                url: '/ui/page-layouts/simple/with-sidebars',
                children: [
                  {
                    id: 'user-interface.page-layouts.simple.with-sidebars.overview',
                    title: 'With Sidebars Overview',
                    translate: 'نمای کلی سایدبار دار',
                    type: 'item',
                    url: '/ui/page-layouts/simple/with-sidebars/overview',
                  },
                  {
                    id: 'user-interface.page-layouts.simple.with-sidebars.normal-scroll',
                    title: 'With Sidebars Normal Scroll',
                    translate: 'اسکرول نرمال ساید بار دار',
                    type: 'item',
                    url: '/ui/page-layouts/simple/with-sidebars/normal-scroll',
                  },
                  {
                    id: 'user-interface.page-layouts.simple.with-sidebars.page-scroll',
                    title: 'With Sidebars Page Scroll',
                    translate: 'اسکرول صفحه سایدبار دار',
                    type: 'item',
                    url: '/ui/page-layouts/simple/with-sidebars/page-scroll',
                  },
                  {
                    id: 'user-interface.page-layouts.simple.with-sidebars.content-scroll',
                    title: 'With Sidebars Content Scroll',
                    translate: 'اسکرول محتوا سایدبار دار',
                    type: 'item',
                    url: '/ui/page-layouts/simple/with-sidebars/content-scroll',
                  },
                ],
              },
            ],
          },
          {
            id: 'user-interface.page-layouts.empty',
            title: 'Empty Page',
            translate: 'صفحه خالی',
            type: 'item',
            url: '/ui/page-layouts/empty',
          },
        ],
      },
      {
        id: 'user-interface.typography',
        title: 'Typography',
        translate: 'تایپوگرافی',
        type: 'item',
        icon: 'heroicons-outline:pencil',
        url: '/ui/typography',
      },
    ],
  },
  {
    id: 'divider-1',
    type: 'divider',
  },
  DocumentationNavigation,
  {
    id: 'auth',
    title: 'Auth',
    translate: 'احراز هویت',
    type: 'group',
    icon: 'verified_user',
    children: [
      {
        id: 'sign-in',
        title: 'Sign in',
        translate: 'ورود',
        type: 'item',
        url: 'sign-in',
        auth: authRoles.onlyGuest,
        icon: 'lock',
      },
      {
        id: 'register',
        title: 'Register',
        translate: 'ثبت نام',
        type: 'item',
        url: 'register',
        auth: authRoles.onlyGuest,
        icon: 'person_add',
      },
      {
        id: 'sign-out',
        title: 'Sign out',
        translate: 'خروج',
        type: 'item',
        auth: authRoles.user,
        url: 'sign-out',
        icon: 'exit_to_app',
      },
      {
        id: 'auth-admin-example',
        title: 'Admin: Auth protected page',
        translate: 'مدیر: صفحه محافظت شده تأیید اعتبار',
        type: 'item',
        url: 'auth/admin-role-example',
        icon: 'security',
      },
      {
        id: 'only-admin-navigation-item',
        title: 'Nav item only for Admin',
        translate: 'آیتم های منو فقط برای مدیر',
        type: 'item',
        auth: authRoles.admin,
        url: 'auth/admin-role-example',
        icon: 'verified_user',
      },
      {
        id: 'auth-staff-example',
        translate: 'کارکنان: صفحه محافظت شده تأیید اعتبار',
        title: 'Staff: Auth protected page',
        type: 'item',
        url: 'auth/staff-role-example',
        icon: 'security',
      },
      {
        id: 'only-staff-navigation-item',
        translate: 'آیتم های منو فقط برای کارکنان',
        title: 'Nav item only for Staff',
        type: 'item',
        auth: authRoles.staff,
        url: 'auth/staff-role-example',
        icon: 'verified_user',
      },
      {
        id: 'auth-guest-example',
        translate: 'مهمان: صفحه محافظت شده تأیید اعتبار',
        title: 'Guest: Auth protected page',
        type: 'item',
        url: 'auth/guest-role-example',
        icon: 'security',
      },
      {
        id: 'only-guest-navigation-item',
        translate: 'آیتم های منو فقط برای مهمان ها',
        title: 'Nav item only for Guest',
        type: 'item',
        auth: authRoles.onlyGuest,
        url: 'auth/guest-role-example',
        icon: 'verified_user',
      },
    ],
  },
  {
    type: 'divider',
    id: 'divider-2',
  },
  {
    id: 'navigation-features',
    translate: 'ویژگی های ناوبری',
    title: 'Navigation features',
    subtitle: 'منوهای بازشو چندسطحی و badge ها',
    type: 'group',
    icon: 'heroicons-outline:menu',
    children: [
      {
        id: 'navigation-features.level.0',
        translate: 'مرحله 0',
        title: 'Level 0',
        icon: 'heroicons-outline:check-circle',
        type: 'collapse',
        children: [
          {
            id: 'navigation-features.level.0.1',
            translate: 'مرحله 1',
            title: 'Level 1',
            type: 'collapse',
            children: [
              {
                id: 'navigation-features.level.0.1.2',
                translate: 'مرحله 2',
                title: 'Level 2',
                type: 'collapse',
                children: [
                  {
                    id: 'navigation-features.level.0.1.2.3',
                    translate: 'مرحله 3',
                    title: 'Level 3',
                    type: 'collapse',
                    children: [
                      {
                        id: 'navigation-features.level.0.1.2.3.4',
                        translate: 'مرحله 4',
                        title: 'Level 4',
                        type: 'collapse',
                        children: [
                          {
                            id: 'navigation-features.level.0.1.2.3.4.5',
                            translate: 'مرحله 5',
                            title: 'Level 5',
                            type: 'collapse',
                            children: [
                              {
                                id: 'navigation-features.level.0.1.2.3.4.5.6',
                                title: 'Level 6',
                                translate: 'مرحله 6',
                                type: 'item',
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'navigation-features2.level.0',
        translate: 'مرحله 0',
        title: 'Level 0',
        subtitle: 'مدل زیرنویس دار',
        icon: 'heroicons-outline:check-circle',
        type: 'collapse',
        children: [
          {
            id: 'navigation-features2.level.0.1-1',
            title: 'Level 1.1',
            translate: 'مرحله 1.1',
            type: 'item',
          },
          {
            id: 'navigation-features2.level.0.1-2',
            title: 'Level 1.2',
            translate: 'مرحله 1.2',
            type: 'item',
          },
        ],
      },
      {
        id: 'navigation-features.active',
        title: 'Active item',
        translate: 'مورد فعال',
        subtitle: 'به طور دستی فعال شده',
        icon: 'heroicons-outline:check-circle',
        type: 'item',
        active: true,
      },
      {
        id: 'navigation-features.disabled-collapse',
        title: 'Disabled collapse',
        translate: 'کالپس غیر فعال ',
        subtitle: 'زیرنویس تستی منو',
        icon: 'heroicons-outline:check-circle',
        type: 'collapse',
        disabled: true,
        children: [
          {
            id: 'navigation-features.disabled-collapse.child',
            title: "You shouldn't be able to see this child",
            translate: "You shouldn't be able to see this child",
            type: 'item',
          },
        ],
      },
      {
        id: 'navigation-features.disabled-item',
        title: 'Disabled item',
        translate: 'مورد غیر فعال',
        subtitle: 'زیرنویس تستی منو',
        icon: 'heroicons-outline:check-circle',
        type: 'item',
        disabled: true,
      },
      {
        id: 'navigation-features.badge-style-oval',
        title: 'Oval badge',
        translate: 'برچسب بیضی شکل',
        icon: 'heroicons-outline:tag',
        type: 'item',
        badge: {
          title: '8',
          translate: '8',
          classes: 'w-20 h-20 bg-teal-400 text-black rounded-full',
        },
      },
      {
        id: 'navigation-features.badge-style-rectangle',
        title: 'Rectangle badge',
        translate: 'برچسب مستطیل شکل',
        icon: 'heroicons-outline:tag',
        type: 'item',
        badge: {
          title: 'Updated!',
          translate: 'Updated',
          classes: 'px-8 bg-teal-400 text-black rounded',
        },
      },
      {
        id: 'navigation-features.badge-style-rounded',
        title: 'Rounded badge',
        translate: 'برچسب دایره ای',
        icon: 'heroicons-outline:tag',
        type: 'item',
        badge: {
          title: 'NEW',
          translate: 'NEW',
          classes: 'px-10 bg-teal-400 text-black rounded-full',
        },
      },
      {
        id: 'navigation-features.badge-style-simple',
        title: 'Simple badge',
        translate: 'برچسب ساده',
        icon: 'heroicons-outline:tag',
        type: 'item',
        badge: {
          title: '87 خوانده نشده',
          classes: 'bg-transparent text-teal-500',
        },
      },
    ],
  },
];

export default navigationConfig;
