const MaterialUIComponentsNavigation = {
  id: 'material-ui-components',
  title: 'کامپوننت های Material UI',
  type: 'collapse',
  icon: 'layers',
  children: [
    {
      id: 'accordion',
      title: 'آکوردیون',
      type: 'item',
      url: '/documentation/material-ui-components/accordion',
    },
    {
      id: 'alert',
      title: 'هشدار',
      type: 'item',
      url: '/documentation/material-ui-components/alert',
    },
    {
      id: 'appBar',
      title: 'نوار برنامه',
      type: 'item',
      url: '/documentation/material-ui-components/app-bar',
    },
    {
      id: 'autocomplete',
      title: 'تکمیل خودکار',
      type: 'item',
      url: '/documentation/material-ui-components/autocomplete',
    },
    {
      id: 'avatars',
      title: 'آواتارها',
      type: 'item',
      url: '/documentation/material-ui-components/avatars',
    },
    {
      id: 'backdrop',
      title: 'پس زمینه',
      type: 'item',
      url: '/documentation/material-ui-components/backdrop',
    },
    {
      id: 'badges',
      title: 'نشان ها',
      type: 'item',
      url: '/documentation/material-ui-components/badges',
    },
    {
      id: 'bottomNavigation',
      title: 'ناوبری پایین',
      type: 'item',
      url: '/documentation/material-ui-components/bottom-navigation',
    },
    {
      id: 'box',
      title: 'جعبه',
      type: 'item',
      url: '/documentation/material-ui-components/box',
    },
    {
      id: 'breadcrumbs',
      title: 'بردکرامب',
      type: 'item',
      url: '/documentation/material-ui-components/breadcrumbs',
    },
    {
      id: 'buttonGroup',
      title: 'گروه دکمه',
      type: 'item',
      url: '/documentation/material-ui-components/button-group',
    },
    {
      id: 'buttons',
      title: 'دکمه ها',
      type: 'item',
      url: '/documentation/material-ui-components/buttons',
    },
    {
      id: 'cards',
      title: 'کارت ها',
      type: 'item',
      url: '/documentation/material-ui-components/cards',
    },
    {
      id: 'checkboxes',
      title: 'چک باکس ها',
      type: 'item',
      url: '/documentation/material-ui-components/checkboxes',
    },
    {
      id: 'chips',
      title: 'چیپ ها',
      type: 'item',
      url: '/documentation/material-ui-components/chips',
    },
    {
      id: 'container',
      title: 'کانتینر',
      type: 'item',
      url: '/documentation/material-ui-components/container',
    },
    {
      id: 'cssBaseline',
      title: 'Css بیس لاین',
      type: 'item',
      url: '/documentation/material-ui-components/css-baseline',
    },
    {
      id: 'dialogs',
      title: 'دیالوگ ها',
      type: 'item',
      url: '/documentation/material-ui-components/dialogs',
    },
    {
      id: 'dividers',
      title: 'تقسیم کننده ها',
      type: 'item',
      url: '/documentation/material-ui-components/dividers',
    },
    {
      id: 'drawers',
      title: 'کشوها',
      type: 'item',
      url: '/documentation/material-ui-components/drawers',
    },
    {
      id: 'floatingActionButton',
      title: ' دکمه اکشن شناور',
      type: 'item',
      url: '/documentation/material-ui-components/floating-action-button',
    },
    {
      id: 'grid',
      title: 'گرید',
      type: 'item',
      url: '/documentation/material-ui-components/grid',
    },
    {
      id: 'grid2',
      title: 'گرید 2',
      type: 'item',
      url: '/documentation/material-ui-components/grid2',
    },
    {
      id: 'imageList',
      title: 'لیست تصاویر',
      type: 'item',
      url: '/documentation/material-ui-components/image-list',
    },
    {
      id: 'links',
      title: 'لینک ها',
      type: 'item',
      url: '/documentation/material-ui-components/links',
    },
    {
      id: 'lists',
      title: 'لیست ها',
      type: 'item',
      url: '/documentation/material-ui-components/lists',
    },
    {
      id: 'masonry',
      title: 'Masonry',
      type: 'item',
      url: '/documentation/material-ui-components/masonry',
    },
    {
      id: 'menus',
      title: 'منو  ها',
      type: 'item',
      url: '/documentation/material-ui-components/menus',
    },
    {
      id: 'modal',
      title: 'مدال',
      type: 'item',
      url: '/documentation/material-ui-components/modal',
    },
    {
      id: 'noSsr',
      title: 'بدون Ssr',
      type: 'item',
      url: '/documentation/material-ui-components/no-ssr',
    },
    {
      id: 'pagination',
      title: 'صفحه بندی',
      type: 'item',
      url: '/documentation/material-ui-components/pagination',
    },
    {
      id: 'paper',
      title: 'کاغذ',
      type: 'item',
      url: '/documentation/material-ui-components/paper',
    },
    {
      id: 'popover',
      title: 'پاپ اور',
      type: 'item',
      url: '/documentation/material-ui-components/popover',
    },
    {
      id: 'popper',
      title: 'پاپر',
      type: 'item',
      url: '/documentation/material-ui-components/popper',
    },
    {
      id: 'portal',
      title: 'پورتال',
      type: 'item',
      url: '/documentation/material-ui-components/portal',
    },
    {
      id: 'progress',
      title: 'پیشرفت',
      type: 'item',
      url: '/documentation/material-ui-components/progress',
    },
    {
      id: 'radioButtons',
      title: 'دکمه های رادیویی',
      type: 'item',
      url: '/documentation/material-ui-components/radio-buttons',
    },
    {
      id: 'rating',
      title: 'رتبه بندی',
      type: 'item',
      url: '/documentation/material-ui-components/rating',
    },
    {
      id: 'selects',
      title: 'سلکت ها',
      type: 'item',
      url: '/documentation/material-ui-components/selects',
    },
    {
      id: 'skeleton',
      title: 'اسکلتون',
      type: 'item',
      url: '/documentation/material-ui-components/skeleton',
    },
    {
      id: 'slider',
      title: 'اسلایدر',
      type: 'item',
      url: '/documentation/material-ui-components/slider',
    },
    {
      id: 'snackbars',
      title: 'اسنک بار',
      type: 'item',
      url: '/documentation/material-ui-components/snackbars',
    },
    {
      id: 'speedDial',
      title: 'Speed Dial',
      type: 'item',
      url: '/documentation/material-ui-components/speed-dial',
    },
    {
      id: 'stack',
      title: 'استک',
      type: 'item',
      url: '/documentation/material-ui-components/stack',
    },
    {
      id: 'steppers',
      title: 'استپرها',
      type: 'item',
      url: '/documentation/material-ui-components/steppers',
    },
    {
      id: 'switches',
      title: 'سوئیچ ها',
      type: 'item',
      url: '/documentation/material-ui-components/switches',
    },
    {
      id: 'table',
      title: 'جدول',
      type: 'item',
      url: '/documentation/material-ui-components/table',
    },
    {
      id: 'tabs',
      title: 'تب ها',
      type: 'item',
      url: '/documentation/material-ui-components/tabs',
    },
    {
      id: 'textFields',
      title: 'فیلدهای متنی',
      type: 'item',
      url: '/documentation/material-ui-components/text-fields',
    },
    {
      id: 'textareaAutosize',
      title: 'اندازه خودکار ناحیه متن',
      type: 'item',
      url: '/documentation/material-ui-components/textarea-autosize',
    },
    {
      id: 'timeline',
      title: 'جدول زمانی',
      type: 'item',
      url: '/documentation/material-ui-components/timeline',
    },
    {
      id: 'toggleButton',
      title: 'دکمه سوئیچ',
      type: 'item',
      url: '/documentation/material-ui-components/toggle-button',
    },
    {
      id: 'tooltips',
      title: 'تولتیپ ها',
      type: 'item',
      url: '/documentation/material-ui-components/tooltips',
    },
    {
      id: 'transferList',
      title: 'لیست انتقال',
      type: 'item',
      url: '/documentation/material-ui-components/transfer-list',
    },
    {
      id: 'transitions',
      title: 'ترنزیشن ها',
      type: 'item',
      url: '/documentation/material-ui-components/transitions',
    },
    {
      id: 'treeView',
      title: 'نمای درختی',
      type: 'item',
      url: '/documentation/material-ui-components/tree-view',
    },
    {
      id: 'typography',
      title: 'تایپوگرافی',
      type: 'item',
      url: '/documentation/material-ui-components/typography',
    },
  ],
};

export default MaterialUIComponentsNavigation;
